export const environment = {
    title: "Development Aromatic Insights",
    title_eo: "Essential Oils",
    title_login: "Login",
    title_register: "Register",
    message_balanced_eo: "Doshas that are reduced by this essential oil",
    message_chemical_list: "List of chemicals in this essential oil ",
    message_latin_name_pre: "Latin name",
    message_modern_name_pre: "Modern name",
    message_balanced_doshas_pre: "Balanced doshas",
    message_chemical_update_form_pre: "Updating ",
    message_name_pre: "Name: ",
    message_category_pre: "Category: ",
    message_welcome: "Welcome to",
    message_username_pre: "Username",
    message_password_pre: "Password",
    message_login_welcome: "Welcome",
    message_password_repeat_pre: "Repeat password",
    button_update: "Update",
    button_delete: "Delete",
    button_close: "Close",
    button_submit: "Submit",
    button_add_chemical: "Add Chemical",
    button_create_eo: "Create New Essential Oil",
    button_register: "Register",
    vata: "Vata",
    pitta: "Pitta",
    kapha: "Kapha",
    page_home: "Home",
    page_essential_oils: "Essential Oils",
    page_login: "Login",
    page_register: "Register",
    page_profile: "Profile",
    page_logout: "Logout"


    
};
